apiVersion: v1
kind: Service
metadata:
  name: gogs-service
  namespace: gogs-prod
  labels:
    app: gogs 
spec:
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30000
  selector:
    app: gogs
  type: NodePort
